services:
  csurfer-service:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: csurfer-dev-image
    container_name: csurfer-container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/home/developer/csurfer
      - /tmp/.X11-unix:/tmp/.X11-unix
    # Access to GPU for smooth rendering
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
