#include "Tab.h"
#include "config/Config.h"
#include "css/CSSParser.h"
#include "css/CSSSelector.h"
#include "css/StyleEngine.h"
#include "gfx/GraphicsContext.h"
#include "html/HTMLParser.h"
#include "js/JSContext.h"
#include "layout/LayoutTree.h"
#include "lexer/Text.h"
#include "utils/Parser.h"
#include "utils/StringUtils.h"
#include <algorithm>
#include <iostream>
#include <sstream>

Tab::Tab(std::shared_ptr<IRequest> network_engine, int window_width,
         gfx::FontManager &font_manager)
    : network_engine_(std::move(network_engine)), window_width_(window_width),
      font_manager_(font_manager), url_("http://localhost/") {}

Tab::~Tab() = default;

void Tab::parse_csp(const std::string &header_value) {
  csp_directives_.clear();
  std::stringstream ss(header_value);
  std::string directive;
  while (std::getline(ss, directive, ';')) {
    directive = utils::trim(directive);
    if (directive.empty())
      continue;

    std::stringstream dss(directive);
    std::string name;
    dss >> name; // First word is directive name (e.g. script-src)

    std::vector<std::string> origins;
    std::string origin;
    while (dss >> origin) {
      if (origin == "'self'") {
        origins.push_back(url_.origin());
      } else {
        origins.push_back(origin);
      }
    }
    csp_directives_[name] = origins;
  }
}

bool Tab::is_allowed(const Url &target_url,
                     const std::string &directive) const {
  if (csp_directives_.empty())
    return true; // Story: No policy = allow all

  std::vector<std::string> allowed;
  if (csp_directives_.count(directive)) {
    allowed = csp_directives_.at(directive);
  } else if (csp_directives_.count("default-src")) {
    allowed = csp_directives_.at("default-src");
  } else {
    return true; // Directive not specified and no default-src
  }

  std::string target_origin = target_url.origin();

  for (const auto &origin : allowed) {
    if (origin == target_origin)
      return true;
  }

  return false;
}

void Tab::load(const Url &url, const std::string &payload) {
  focused_element_ = nullptr;
  if (history_.empty() || history_.back().href() != url.href()) {
    history_.push_back(url);
  }

  Url referrer = url_;
  url_ = url;
  std::cout << "[Tab] Navigating to: " << url_.href() << std::endl;

  std::string body;
  if (url_.href() == "about:welcome") {
    // Story: Hardcoded welcome page for new users
    body = "<html><head><title>Welcome</title></head><body>"
           "<div style=\"text-align:center; padding:50px;\">"
           "<h1>Welcome in CSurfer</h1>"
           "<p>Your lightweight, SOLID-powered browser.</p>"
           "<hr><p>Visit the project on GitHub:</p>"
           "<a href=\"https://github.com/mohamedhany01/csurfer\">"
           "mohamedhany01/csurfer</a><br><br>"
           "<p>Local Test Pages:</p>"
           "<a href=\"http://localhost:8000/\">http://localhost:8000/</a>"
           "<br><br><p><i>Enjoy surfing the solid way!</i></p>"
           "</div></body></html>";
  } else {
    try {
      auto response = network_engine_->request(url_, payload, referrer);
      body = response.body;

      if (response.headers.count("content-security-policy")) {
        parse_csp(response.headers.at("content-security-policy"));
      } else {
        csp_directives_.clear();
      }
    } catch (const std::exception &error) {
      load_error_page(std::string("Network Error: ") + error.what());
      return;
    }
  }

  if (body.empty()) {
    body = "<html><body><h1>Error Loading Page</h1>"
           "<p>We couldn't reach <b>" +
           url_.href() + "</b>. Check the URL and try again.</p></body></html>";
  }

  load_error_page(body);
}

void Tab::load_error_page(const std::string &content_or_message) {
  std::string body = content_or_message;

  // Story: If it's just a message (no tags), wrap it in HTML
  if (body.find('<') == std::string::npos) {
    body = "<html><body style=\"padding:20px; font-family:sans-serif;\">"
           "<h1 style=\"color:red;\">Navigation Error</h1>"
           "<p>" +
           body +
           "</p><hr>"
           "<p><small>Generated by C Surfer Engine</small></p>"
           "</body></html>";
  }

  HTMLParser parser(body);
  root_ = parser.parse();

  StyleEngine style_engine(network_engine_);
  style_engine.apply(
      dynamic_cast<Element *>(root_.get()), url_,
      [this](const Url &u, const std::string &d) { return is_allowed(u, d); },
      url_);

  document_layout_ = std::make_unique<DocumentLayout>(
      root_.get(), font_manager_, window_width_);
  document_layout_->layout();

  display_list_.clear();
  paint_tree(*document_layout_, display_list_);
  current_scroll_ = 0;
  javascript_context_ = std::make_unique<JSContext>(this);

  // Story: Find and run all <script> tags in the document
  auto selector = CSSParser::parse_selector("script");
  if (selector && root_) {
    std::vector<Element *> scripts;
    std::function<void(Element *)> find_scripts =
        [&](Element *element) -> void {
      if (selector->matches(element)) {
        scripts.push_back(element);
      }
      for (auto &child_lexeme : element->children()) {
        if (child_lexeme->type() == LexemeType::Element) {
          find_scripts(static_cast<Element *>(child_lexeme.get()));
        }
      }
    };
    find_scripts(dynamic_cast<Element *>(root_.get()));

    for (auto *script : scripts) {
      auto attributes = script->attributes();
      if (attributes.count("src")) {
        std::string script_url_string = attributes.at("src");
        try {
          Url resolved_script_url = url_.resolve(script_url_string);

          if (!is_allowed(resolved_script_url, "script-src")) {
            std::cout << "[SOP/CSP] Blocked script loading from: "
                      << script_url_string << " (CSP Violation)" << std::endl;
            continue;
          }

          std::cout << "[Tab] Loading external script: " << script_url_string
                    << std::endl;
          std::string script_content =
              network_engine_->request(resolved_script_url, "", url_).body;
          if (!script_content.empty()) {
            javascript_context_->run(script_url_string, script_content);
          }
        } catch (const std::exception &) {
          // Skip malformed script URLs
        }
      } else {
        std::string inline_content;
        for (auto &child_lexeme : script->children()) {
          if (child_lexeme->type() == LexemeType::Text) {
            inline_content += child_lexeme->text();
          }
        }
        if (!inline_content.empty()) {
          javascript_context_->run("inline", inline_content);
        }
      }
    }
  }
}

void Tab::rebuild_layout() {
  if (!root_)
    return;
  StyleEngine style_engine(network_engine_);
  style_engine.apply(
      dynamic_cast<Element *>(root_.get()), url_,
      [this](const Url &u, const std::string &d) { return is_allowed(u, d); },
      url_);
  document_layout_ = std::make_unique<DocumentLayout>(
      root_.get(), font_manager_, window_width_);
  document_layout_->layout();
  display_list_.clear();
  paint_tree(*document_layout_, display_list_);
}

void Tab::render(gfx::GraphicsContext &ctx, int y_screen_offset) const {
  if (!document_layout_)
    return;
  for (const auto &command : display_list_) {
    command->execute(current_scroll_, y_screen_offset, ctx);
  }
  render_scrollbar(ctx, y_screen_offset);
}

void Tab::render_scrollbar(gfx::GraphicsContext &ctx,
                           int y_screen_offset) const {
  if (!document_layout_)
    return;

  int viewport_height = config::WINDOW_HEIGHT - y_screen_offset;
  int document_height = (int)document_layout_->bounds().height + 60;

  if (document_height <= viewport_height)
    return; // Story: No need to scroll if content fits in viewport

  int bar_width = config::SCROLLBAR_WIDTH;
  int bar_x = window_width_ - bar_width;

  // Story: Draw the Scrollbar Track
  ctx.draw_rect({{bar_x, y_screen_offset}, bar_width, viewport_height},
                gfx::Color::from_rgb(240, 240, 240));

  // Story: Draw the Scrollbar Thumb
  double thumb_ratio = (double)viewport_height / document_height;
  int thumb_height = (int)(viewport_height * thumb_ratio);
  if (thumb_height < 20)
    thumb_height = 20; // Minimum size

  double scroll_ratio =
      (double)current_scroll_ / (document_height - viewport_height);
  int thumb_y =
      y_screen_offset + (int)(scroll_ratio * (viewport_height - thumb_height));

  ctx.draw_rect({{bar_x + 2, thumb_y}, bar_width - 4, thumb_height},
                gfx::Color::from_rgb(160, 160, 160));
}

void Tab::handle_mousedown(int x, int y) {
  if (!document_layout_)
    return;

  int ui_height = config::UI_HEIGHT;
  int viewport_height = config::WINDOW_HEIGHT - ui_height;
  int document_height = (int)document_layout_->bounds().height + 100;

  if (document_height > viewport_height &&
      x >= window_width_ - config::SCROLLBAR_WIDTH) {
    is_dragging_scrollbar_ = true;
    handle_mousemove(x, y);
    return;
  }

  click(x, y);
}

void Tab::handle_mousemove(int x, int y) {
  if (!is_dragging_scrollbar_ || !document_layout_)
    return;

  int ui_height = config::UI_HEIGHT;
  int viewport_height = config::WINDOW_HEIGHT - ui_height;
  int document_height = (int)document_layout_->bounds().height + 100;

  double scroll_ratio = (double)y / viewport_height;
  int max_scroll = std::max(0, document_height - viewport_height);
  current_scroll_ = std::min(
      max_scroll,
      std::max(0, (int)(scroll_ratio * document_height - viewport_height / 2)));
}

void Tab::handle_mouseup(int /*x*/, int /*y*/) {
  is_dragging_scrollbar_ = false;
}

void Tab::click(int x, int y) {
  if (!document_layout_)
    return;

  auto total_y = y + current_scroll_;

  auto all_nodes = tree_to_list(*document_layout_);
  const Lexeme *clicked_node = nullptr;

  for (auto it = all_nodes.rbegin(); it != all_nodes.rend(); ++it) {
    const LayoutObject *object = *it;
    if (object->bounds().contains({x, total_y})) {
      clicked_node = object->node();
      if (clicked_node)
        break;
    }
  }

  if (clicked_node) {
    if (focused_element_) {
      focused_element_->set_focused(false);
    }
    focused_element_ = nullptr;

    const Lexeme *current_lexeme = clicked_node;
    while (current_lexeme) {
      if (current_lexeme->type() == LexemeType::Element) {
        const auto *element = dynamic_cast<const Element *>(current_lexeme);
        if (element) {
          if (javascript_context_ &&
              javascript_context_->dispatch_event(
                  "click", const_cast<Element *>(element))) {
            return;
          }
          if (element->tag() == "a" && element->attributes().contains("href")) {
            try {
              load(url_.resolve(element->attributes().at("href")));
            } catch (const utils::UrlError &error) {
              load_error_page(error.what());
            }
            return;
          } else if (element->tag() == "input") {
            focused_element_ = const_cast<Element *>(element);
            focused_element_->set_focused(true);
            focused_element_->set_attribute("value", "");

            display_list_.clear();
            paint_tree(*document_layout_, display_list_);
            return;
          } else if (element->tag() == "button") {
            const Element *form_search = element;
            while (form_search) {
              if (form_search->tag() == "form" &&
                  form_search->attributes().contains("action")) {
                submit_form(form_search);
                return;
              }
              form_search =
                  dynamic_cast<const Element *>(form_search->parent());
            }
          }
        }
      }
      current_lexeme = current_lexeme->parent();
    }
  }

  display_list_.clear();
  paint_tree(*document_layout_, display_list_);
}

void Tab::handle_keypress(SDL_Keycode key, const std::string &text) {
  if (!focused_element_)
    return;

  auto *element = dynamic_cast<Element *>(focused_element_);
  if (!element)
    return;

  if (javascript_context_ &&
      javascript_context_->dispatch_event("keydown", element)) {
    return;
  }

  auto attributes = element->attributes();
  std::string value_string =
      attributes.count("value") ? attributes.at("value") : "";

  if (key == SDLK_BACKSPACE) {
    if (!value_string.empty()) {
      value_string.pop_back();
    }
  } else if (!text.empty()) {
    value_string += text;
  }

  element->set_attribute("value", value_string);

  document_layout_->layout();
  display_list_.clear();
  paint_tree(*document_layout_, display_list_);
}

void Tab::submit_form(const Element *form_element) {
  if (!form_element)
    return;

  if (javascript_context_ &&
      javascript_context_->dispatch_event(
          "submit", const_cast<Element *>(form_element))) {
    return;
  }

  std::string payload_string;

  std::vector<const Lexeme *> queue = {form_element};
  while (!queue.empty()) {
    const Lexeme *node = queue.front();
    queue.erase(queue.begin());

    if (node->type() == LexemeType::Element) {
      const auto *element = dynamic_cast<const Element *>(node);
      if (element->tag() == "input" && element->attributes().contains("name")) {
        std::string name = element->attributes().at("name");
        std::string value = element->attributes().count("value")
                                ? element->attributes().at("value")
                                : "";
        if (!payload_string.empty())
          payload_string += "&";
        payload_string += utils::url_percent_encode(name) + "=" +
                          utils::url_percent_encode(value);
      }
      for (const auto &child : element->children()) {
        queue.push_back(child.get());
      }
    }
  }

  std::string action_url_string = form_element->attributes().at("action");
  std::cout << "[Tab] Submitting form to: " << action_url_string
            << " with payload: " << payload_string << std::endl;
  try {
    load(url_.resolve(action_url_string), payload_string);
  } catch (const utils::UrlError &error) {
    load_error_page(error.what());
  }
}

void Tab::scroll_down() {
  if (!document_layout_)
    return;
  int total_content_height = (int)document_layout_->bounds().height + 60;
  int max_scroll_offset = std::max(
      0, total_content_height - (config::WINDOW_HEIGHT - config::UI_HEIGHT));
  current_scroll_ =
      std::min(current_scroll_ + config::SCROLL_STEP, max_scroll_offset);
}

void Tab::scroll_up() {
  current_scroll_ = std::max(0, current_scroll_ - config::SCROLL_STEP);
}

void Tab::go_back() {
  if (history_.size() > 1) {
    history_.pop_back();
    Url previous_url = history_.back();
    history_.pop_back();
    std::cout << "[Tab] Going back to: " << previous_url.href() << std::endl;
    load(previous_url);
  }
}

const std::string Tab::title() const {
  if (!root_)
    return url_.host();

  // Story: Search for the <title> tag in the DOM tree
  std::vector<const Lexeme *> queue = {root_.get()};
  while (!queue.empty()) {
    const Lexeme *node = queue.front();
    queue.erase(queue.begin());

    if (node->type() == LexemeType::Element) {
      const auto *element = dynamic_cast<const Element *>(node);
      if (element->tag() == "title" && !element->children().empty()) {
        const auto *text_node =
            dynamic_cast<const Text *>(element->children().front().get());
        if (text_node)
          return text_node->text();
      }
      for (const auto &child : element->children()) {
        queue.push_back(child.get());
      }
    }
  }

  return url_.host();
}
