#include "Tab.h"
#include "config/Config.h"
#include "css/CSSParser.h"
#include "css/CSSSelector.h"
#include "css/StyleEngine.h"
#include "dom/Text.h"
#include "gfx/GraphicsContext.h"
#include "html/HTMLParser.h"
#include "js/JSContext.h"
#include "layout/LayoutTree.h"
#include "utils/Logger.h"
#include "utils/Parser.h"
#include "utils/StringUtils.h"
#include <algorithm>
#include <sstream>

Tab::Tab(std::shared_ptr<IRequest> network_engine, int window_width,
         gfx::FontManager &font_manager)
    : window_width_(window_width), font_manager_(font_manager),
      navigator_(std::move(network_engine)) {}

Tab::~Tab() = default;

void Tab::load(const Url &url, const std::string &payload) {
  focused_element_ = nullptr;
  std::string body = navigator_.load(url, payload, security_policy_);
  process_document(body);
}

/**
 * Story: The core pipeline for processing a new HTML document.
 * It parses the HTML, applies styles, computes the layout, and
 * initializes the JavaScript environment.
 */
void Tab::process_document(const std::string &content_or_message) {
  std::string body = content_or_message;

  // Story: If it's just a message (no tags), wrap it in HTML
  if (body.find('<') == std::string::npos) {
    body = "<html><body style=\"padding:20px; font-family:sans-serif;\">"
           "<h1 style=\"color:red;\">Navigation Error</h1>"
           "<p>" +
           body +
           "</p><hr>"
           "<p><small>Generated by C Surfer Engine</small></p>"
           "</body></html>";
  }

  HTMLParser parser(body);
  root_ = parser.parse();

  StyleEngine style_engine(navigator_.network_engine());
  style_engine.apply(
      dynamic_cast<Element *>(root_.get()), navigator_.url(),
      [this](const Url &u, const std::string &d) {
        return security_policy_.is_allowed(u, d);
      },
      navigator_.url());

  document_layout_ = std::make_unique<DocumentLayout>(
      root_.get(), font_manager_, window_width_);
  document_layout_->layout();

  renderer_.rebuild_display_list(*document_layout_);
  renderer_.set_scroll(0);
  javascript_context_ = std::make_unique<JSContext>(this);

  process_scripts();
}

/**
 * Story: Scans the DOM tree for all <script> tags and executes them.
 * External scripts are fetched from the network, while inline scripts
 * are executed directly. Respects Content Security Policy (CSP).
 */
void Tab::process_scripts() {
  auto selector = CSSParser::parse_selector("script");
  if (!selector || !root_)
    return;

  std::vector<Element *> scripts;
  std::function<void(Element *)> find_scripts = [&](Element *element) -> void {
    if (selector->matches(element)) {
      scripts.push_back(element);
    }
    for (auto &child_lexeme : element->children()) {
      if (child_lexeme->type() == LexemeType::Element) {
        find_scripts(static_cast<Element *>(child_lexeme.get()));
      }
    }
  };
  find_scripts(dynamic_cast<Element *>(root_.get()));

  for (auto *script : scripts) {
    auto attributes = script->attributes();
    if (attributes.count("src")) {
      std::string script_url_string = attributes.at("src");
      try {
        Url resolved_script_url = navigator_.url().resolve(script_url_string);

        if (!security_policy_.is_allowed(resolved_script_url, "script-src")) {
          std::cout << "[SOP/CSP] Blocked script loading from: "
                    << script_url_string << " (CSP Violation)" << std::endl;
          continue;
        }

        std::cout << "[Tab] Loading external script: " << script_url_string
                  << std::endl;
        std::string script_content =
            navigator_.network_engine()
                ->request(resolved_script_url, "", navigator_.url())
                .body;
        if (!script_content.empty()) {
          javascript_context_->run(script_url_string, script_content);
        }
      } catch (const std::exception &) {
        // Skip malformed script URLs
      }
    } else {
      std::string inline_content;
      for (auto &child_lexeme : script->children()) {
        if (child_lexeme->type() == LexemeType::Text) {
          inline_content += child_lexeme->text();
        }
      }
      if (!inline_content.empty()) {
        javascript_context_->run("inline", inline_content);
      }
    }
  }
}

void Tab::rebuild_layout() {
  if (!root_)
    return;
  StyleEngine style_engine(navigator_.network_engine());
  style_engine.apply(
      dynamic_cast<Element *>(root_.get()), navigator_.url(),
      [this](const Url &u, const std::string &d) {
        return security_policy_.is_allowed(u, d);
      },
      navigator_.url());
  document_layout_ = std::make_unique<DocumentLayout>(
      root_.get(), font_manager_, window_width_);
  document_layout_->layout();
  renderer_.rebuild_display_list(*document_layout_);
}

void Tab::render(gfx::GraphicsContext &ctx, int y_screen_offset) const {
  if (!document_layout_)
    return;
  int document_height = (int)document_layout_->bounds().height + 60;
  renderer_.render(ctx, y_screen_offset, config::WINDOW_HEIGHT, document_height,
                   window_width_);
}

void Tab::handle_mousedown(int x, int y) {
  if (!document_layout_)
    return;

  int ui_height = config::UI_HEIGHT;
  int viewport_height = config::WINDOW_HEIGHT - ui_height;
  int document_height = (int)document_layout_->bounds().height + 100;

  if (document_height > viewport_height &&
      x >= window_width_ - config::SCROLLBAR_WIDTH) {
    renderer_.set_dragging_scrollbar(true);
    handle_mousemove(x, y);
    return;
  }

  click(x, y);
}

void Tab::handle_mousemove(int x, int y) {
  if (!renderer_.is_dragging_scrollbar() || !document_layout_)
    return;

  int ui_height = config::UI_HEIGHT;
  int viewport_height = config::WINDOW_HEIGHT - ui_height;
  int document_height = (int)document_layout_->bounds().height + 100;

  double scroll_ratio = (double)y / viewport_height;
  int max_scroll = std::max(0, document_height - viewport_height);
  renderer_.set_scroll(
      std::min(max_scroll, std::max(0, (int)(scroll_ratio * document_height -
                                             viewport_height / 2))));
}

void Tab::handle_mouseup(int /*x*/, int /*y*/) {
  renderer_.set_dragging_scrollbar(false);
}

void Tab::click(int x, int y) {
  if (!document_layout_)
    return;

  auto total_y = y + renderer_.current_scroll();

  auto all_nodes = tree_to_list(*document_layout_);
  const Lexeme *clicked_node = nullptr;

  for (auto it = all_nodes.rbegin(); it != all_nodes.rend(); ++it) {
    const LayoutObject *object = *it;
    if (object->bounds().contains({x, total_y})) {
      clicked_node = object->node();
      if (clicked_node)
        break;
    }
  }

  if (clicked_node) {
    if (focused_element_) {
      focused_element_->set_focused(false);
    }
    focused_element_ = nullptr;

    const Lexeme *current_lexeme = clicked_node;
    while (current_lexeme) {
      if (current_lexeme->type() == LexemeType::Element) {
        const auto *element = dynamic_cast<const Element *>(current_lexeme);
        if (element) {
          if (javascript_context_ &&
              javascript_context_->dispatch_event(
                  "click", const_cast<Element *>(element))) {
            return;
          }
          if (element->tag() == "a" && element->attributes().contains("href")) {
            try {
              load(navigator_.url().resolve(element->attributes().at("href")));
            } catch (const utils::UrlError &error) {
              process_document(error.what());
            }
            return;
          } else if (element->tag() == "input") {
            focused_element_ = const_cast<Element *>(element);
            focused_element_->set_focused(true);
            focused_element_->set_attribute("value", "");

            renderer_.rebuild_display_list(*document_layout_);
            return;
          } else if (element->tag() == "button") {
            const Element *form_search = element;
            while (form_search) {
              if (form_search->tag() == "form" &&
                  form_search->attributes().contains("action")) {
                submit_form(form_search);
                return;
              }
              form_search =
                  dynamic_cast<const Element *>(form_search->parent());
            }
          }
        }
      }
      current_lexeme = current_lexeme->parent();
    }
  }

  renderer_.rebuild_display_list(*document_layout_);
}

void Tab::handle_keypress(SDL_Keycode key, const std::string &text) {
  if (!focused_element_)
    return;

  auto *element = dynamic_cast<Element *>(focused_element_);
  if (!element)
    return;

  if (javascript_context_ &&
      javascript_context_->dispatch_event("keydown", element)) {
    return;
  }

  auto attributes = element->attributes();
  std::string value_string =
      attributes.count("value") ? attributes.at("value") : "";

  if (key == SDLK_BACKSPACE) {
    if (!value_string.empty()) {
      value_string.pop_back();
    }
  } else if (!text.empty()) {
    value_string += text;
  }

  element->set_attribute("value", value_string);

  document_layout_->layout();
  renderer_.rebuild_display_list(*document_layout_);
}

void Tab::submit_form(const Element *form_element) {
  if (!form_element)
    return;

  if (javascript_context_ &&
      javascript_context_->dispatch_event(
          "submit", const_cast<Element *>(form_element))) {
    return;
  }

  std::string payload_string;

  std::vector<const Lexeme *> queue = {form_element};
  while (!queue.empty()) {
    const Lexeme *node = queue.front();
    queue.erase(queue.begin());

    if (node->type() == LexemeType::Element) {
      const auto *element = dynamic_cast<const Element *>(node);
      if (element->tag() == "input" && element->attributes().contains("name")) {
        std::string name = element->attributes().at("name");
        std::string value = element->attributes().count("value")
                                ? element->attributes().at("value")
                                : "";
        if (!payload_string.empty())
          payload_string += "&";
        payload_string += utils::url_percent_encode(name) + "=" +
                          utils::url_percent_encode(value);
      }
      for (const auto &child : element->children()) {
        queue.push_back(child.get());
      }
    }
  }

  std::string action_url_string = form_element->attributes().at("action");
  CS_LOG_INFO("Submitting form to: {} with payload: {}", action_url_string,
              payload_string);
  try {
    load(navigator_.url().resolve(action_url_string), payload_string);
  } catch (const utils::UrlError &error) {
    process_document(error.what());
  }
}

void Tab::scroll_down() {
  if (!document_layout_)
    return;
  int document_height = (int)document_layout_->bounds().height + 60;
  renderer_.scroll_down(document_height, config::WINDOW_HEIGHT);
}

void Tab::scroll_up() { renderer_.scroll_up(); }

void Tab::go_back() {
  if (auto previous_url = navigator_.go_back()) {
    CS_LOG_INFO("Going back to: {}", previous_url->href());
    load(*previous_url);
  }
}

const std::string Tab::title() const {
  if (!root_)
    return navigator_.url().host();

  // Story: Search for the <title> tag in the DOM tree
  std::vector<const Lexeme *> queue = {root_.get()};
  while (!queue.empty()) {
    const Lexeme *node = queue.front();
    queue.erase(queue.begin());

    if (node->type() == LexemeType::Element) {
      const auto *element = dynamic_cast<const Element *>(node);
      if (element->tag() == "title" && !element->children().empty()) {
        const auto *text_node =
            dynamic_cast<const Text *>(element->children().front().get());
        if (text_node)
          return text_node->text();
      }
      for (const auto &child : element->children()) {
        queue.push_back(child.get());
      }
    }
  }

  return navigator_.url().host();
}
