name: C++ CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      env:
        CI: true
      run: ./scripts/setup.sh
    - name: Cache Skia
      id: cache-skia
      uses: actions/cache@v4
      with:
        path: external/skia
        key: ${{ runner.os }}-skia-build-v1
    
    - name: Build
      run: ./scripts/rebuild.sh

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        env:
          CI: true
        run: ./scripts/setup.sh
      - name: Cache Skia
        id: cache-skia
        uses: actions/cache@v4
        with:
          path: external/skia
          key: ${{ runner.os }}-skia-build-v1

      - name: Build Release
        run: |
          if [ ! -f "external/skia/out/Static/libskia.a" ]; then
              echo "[Info] Skia library not found. Building..."
              ./scripts/internal/build_skia.sh
          fi
          cmake --preset release
          cmake --build --preset release -v
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-release/csurfer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
